server:
  port: 7777

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: false
      fail_on_empty_beans: false
    default-property-inclusion: non_empty

